version: '3'
services:
  tests:
    environment:
      - SELENIUM_BASE_URL=http://selenium-chrome:4444
      - SELENIUM_BROWSER=chrome
      - AEM_AUTHOR_URL
      - AEM_AUTHOR_USERNAME
      - AEM_AUTHOR_PASSWORD
      - AEM_PUBLISH_URL
      - AEM_PUBLISH_USERNAME
      - AEM_PUBLISH_PASSWORD
      - REPORTS_PATH=/tmp/reports/wdio-chrome
      - SHARED_FOLDER=/tmp/shared
      - HEADLESS_BROWSER
    shm_size: '2gb'
    volumes:
      - ./target/reports:/tmp/reports
      - 'shared:/tmp/shared'
      - 'shared:/usr/src/app/assets'
    image: '201076423/aem:java1'
  selenium-chrome:
    image: 'selenium/standalone-chrome-debug:latest'
    ports:
      - 4444:4444
    volumes:
      - 'shared:/tmp/shared'
volumes:
  shared:
